version: "3.8"
services:
  jekyll:
    image: jekyll/jekyll:latest
    working_dir: /srv/jekyll
    volumes:
      - ./docs:/srv/jekyll
    ports:
      - 4000:4000
    command: jekyll serve --watch --force_polling --verbose --host 0.0.0.0 --port 4000